
##### Source files #####

# Path to an ENSEMBL FASTA reference transcriptome file/URL to be used for read mapping (local, FTP or HTTP)

transcriptome_ref: "data/yeast/reference/reference_transcriptome.fa"

##### Conditional execution of pipeline #####

gpu_acceleration: False
quality_control: True
nanocompore: True
tombo: True
differr: True
eligos2: True
xpore: False
mines: False
epinano: False

##### Individual rules configuration #####

get_transcriptome:
    threads: 1
    mem_mb: 1000
    opt: ""

ont_guppy:
    threads: 4
    mem_mb: 6000
    opt: "-c rna_r9.4.1_70bps_hac.cfg --records_per_fastq 0 --recursive --disable_pings --calib_detect --num_callers 4 --cpu_threads_per_caller 1"
    # example GPU options if using gpu_basecalling instead
    #opt: "-c rna_r9.4.1_70bps_hac.cfg --records_per_fastq 0 --recursive --disable_pings --calib_detect --num_callers 8 --gpu_runners_per_device 1 --device 'auto'"

merge_fastq:
    threads: 1
    mem_mb: 1000
    opt: "--remove_duplicates --min_len 100 --min_qual 7"

minimap2_index:
    threads: 1
    mem_mb: 1000
    opt: ""

minimap2_align:
    threads: 4
    mem_mb: 1000
    opt: "-a -L -x map-ont"

alignmemt_reads_index:
    threads: 1
    mem_mb: 1000
    opt: "--skip_unmapped --skip_secondary --skip_supplementary"

alignmemt_prefilter:
    threads: 1
    mem_mb: 1000
    opt: "--skip_unmapped --skip_secondary --skip_supplementary --index_reads --orientation '+' --min_read_len 100 --min_align_len 100 --min_mapq 10 --min_freq_identity 0.8"

min_ref_coverage:
    threads: 1
    mem_mb: 1000
    opt:
        min_cov: 30

alignmemt_postfilter:
    threads: 1
    mem_mb: 1000
    opt: "--index_reads"

alignmemt_merge:
    threads: 4
    mem_mb: 1000
    opt: ""

f5c_index:
    threads: 4
    mem_mb: 1000
    opt: "--iop 4"

f5c_eventalign:
    threads: 4
    mem_mb: 1000
    opt: "-x laptop-low --rna --samples --signal-index --print-read-names --scale-events --kmer-model resources/r9.4_70bps.u_to_t_rna.5mer.template.model"

# Nanopolish parameters

nanopolish_index:
    threads: 4
    mem_mb: 1000
    opt: ""

alignment_split:
    threads: 1
    mem_mb: 1000
    opt: "--index"
    n_chunks: 3 #### Can be increased to speed up nanopolish

nanopolish_eventalign:
    threads: 4
    mem_mb: 1000
    opt: "--samples --print-read-names --scale-events --signal-index" # Options required for nanocompore and xpore

eventalign_merge:
    threads: 1
    mem_mb: 1000
    opt: ""

# nanocompore parameters

nanocompore_eventalign_collapse:
    threads: 4
    mem_mb: 1000
    opt: ""

nanocompore_sampcomp:
    threads: 4
    mem_mb: 1000
    opt: "--max_invalid_kmers_freq 0.2 --min_coverage 30 --downsample_high_coverage 5000 --min_ref_length 100 --comparison_methods GMM,KS --sequence_context 2 --sequence_context_weights harmonic --pvalue_thr 0.01 --logit"

nanocompore_postprocess:
    threads: 1
    mem_mb: 1000
    opt: ""

# tombo parameters

tombo_preprocess:
    threads: 4
    mem_mb: 1000
    opt: ""

tombo_detect_modifications:
    threads: 4
    mem_mb: 1000
    opt: "--minimum-test-reads 50 --fishers-method-context 2 --statistic-type ks --store-p-value"

tombo_postprocess:
    threads: 1
    mem_mb: 1000
    opt:
        min_cov: 50
        p_val_lim: 0.01
        quantile_lim: 0.5
        min_distance: 9

# differr parameters

differr_compare:
    threads: 4
    mem_mb: 1000
    opt: "--normalise --max-depth 5000 --fdr-threshold 0.01 --median-expr-threshold 30 --min-expr-threshold 30"

differr_postprocess:
    threads: 1
    mem_mb: 1000
    opt: ""


# eligos2 parameters

eligos2_fasta_to_bed:
    threads: 1
    mem_mb: 1000
    opt: ""

eligos2_pair_diff_mod:
    threads: 4
    mem_mb: 1000
    opt: "--oddR 0 --esb 0 --min_depth 30"
    #--oddR 1.2 --pval 0.01 --adjPval 0.01

# quality_control parameters

pycoQC:
    threads: 1
    mem_mb: 1000
    opt: "--skip_coverage_plot --filter_calibration --filter_duplicated --min_pass_len 100 --min_pass_qual 7"
